title: rants
description: > 
  "Disclaimer: please test & verify everything I rant about."

show_excerpts: false

minima:
  social_links:
    - { platform: twitter, user_url: "https://twitter.com/blackbeard0x14e" }
    - { platform: github,  user_url: "https://github.com/blackbeard334" }

remote_theme: jekyll/minima
