title: rants
description: > 
  "Disclaimer: please test & verify everything I rant about."

show_excerpts: true

minima:
  social_links:
    twitter: blackbeard0x14e
    github:  blackbeard334

remote_theme: jekyll/minima
